### ISSUE TITLE
Bottom footer to toggle between main pages (Home, Search, future Profile) 

### ISSUE THREAD

**Issue by simonv3** [resonatecoop/mobile#16]
![image](https://user-images.githubusercontent.com/485583/178118534-ea459d54-31cb-4a96-9d02-3355528c4df4.png)

This should probably be done first.

**Comment by peterklingelhofer** [comment]
Haven't used React Navigation before, but this [component](https://reactnavigation.org/docs/bottom-tab-navigator) looks interesting for this.
