### ISSUE TITLE
Smooth Scrolling

### ISSUE THREAD

**Issue by glottis0q** [resonatecoop/mobile#22]
Please disable smooth scrolling as it just feels weird. It feels like the device scrolls not beneath my finger but figures it’s own position. Thanks

**Comment by simonv3** [comment]
Hey @glottis0q there's absolutely nothing with scrolling in this repo yet. Are you maybe looking for [stream-app](https://github.com/peterklingelhofer/stream-app)?

**Comment by glottis0q** [comment]
Maybe, I thought the linked repository was moved to this one. Sry

**Comment by simonv3** [comment]
We'll be doing dev here in the future, but some [maintenance stuff](https://community.resonate.coop/t/warning-resonate-infrastructure-in-flux-coming-week-s-effective-immediately/3159/9) needs to be done first and is taking priority now

**Comment by glottis0q** [comment]
ah, alright. Got it
